language: node_js
env:
  global:
  - secure: yTWXodgyRx308b2IcSq+wl89LcuSTXXkoX1yJ9pFDbbbGeXsOAMBpeKtwuhdjfj+dNHgsNq5MHowuH3hkFjRolZYGjc+hfvmn1skriXGuyzcIL01U8nLJYfsBgjJ5K88HJTKPGktn3+SDQkWlfK1qTezR5O2lmXFa7hEUzFxV+YDCpICaFmIf7TGZk3g4knxt19NrqhiLA5P54u+qBhoKuA/iFpHjDpXrq9OdvJGc8mShA0gX0e/jip8T6otklJSdoCy3eHo5KDqC5AcXKyepaNL4fZubkg9w7fSb5Z0sTtg6+QfmQzUdeR5M++CDUnVUCAKySVC/PSN7Fbf+JTyVNezl6Ixtrv3LuR3XEXd7freq/tiUsdkrHJF69UApPdP9L53MhZY3hpulEnFYUuuECiD4H5L7seJIXHiDBdADfb6Dv15/WQn4YNwVgzZuP59SrGDV7xOsGqyNdPoEAEI8OcH5Cu1TJKy3AM29HkQt5PSb/DesgLwD/ngC9IN7a1/SV/LqovPl+r+WH4XRHonlPMe0a1sQuGdOSWWWQRXxHGGm0EqkbTn9RpD9IltaswPted5hNAaHXu2lMWgQ+Cn9l31B9yLI4Yxk+JQgQiHKqYVprGlADToSjQrMRR/k8YcRm9qYpey9R5pUQc4TEU7X6jWWFR4Br4cm8XO5aphXPY=
  - secure: BB6wNTQrRkCtQRWyt5qNH8ybWIR8hKzKS4LDZ3VsjY+dypWMN7KgslTnb/9JDbvUFcifKs3je46SCmemHUVpCcThnyxaU1nIUsiaQ0bQuy57HoB5lblDU7MpAIr4LE8m7RE7RzkUAboTzrMCeAhFBjNzTBvfJVUrzvdLJWhmmKuRu3QQ1xTQ1QSLFEjiCf9e4eIfZYrp6VoUGKlRoZrUHr7T1ztj0h8WNtxFZnlOP/Nxq66UlexxiIYOV2BH2leqjgECjEzeDVaTg8+s6Xkr4bUN0XNbpCwIiZX3UYCIqYNUGxakYtzjVJWrfe+hq8chR7TrCNCqZzwdrqzd8e+IDO0ruRs0/2iT1yi1nZe7zLHALB9Q1kamxoi72FbabSoO5Hvgs7pnUm5FtZnz07QjWdkiIMSCJo90dYQrdxhtfML2x9WWV/SpScfrwj2lXFLwPukUP6vuLJ7UjqHwGPFKUWSMtn6NRmgXnItVJqIfSrlDLSqj2h+cetokpACzCN0AKaR7uVbn1WN0ITIK6Y+7qsi6+f9p+iLn9Nl3gWTRYrcHdHbkny8JI1g/Fc4T8m5AeQwP3yDu/Ms79K68uZqXi5O2FDsx/xpzT00s0fcx9cCShsKjkf3LFGhBOK8fUK+8yqKBduJAgy21ZdUi7x05hjQ06hljHHLows3pKsEZmFM=
  - secure: seqGpNO2S8DWKndzz/ZseTXEF+dYsAgmnK5U7a+TxhrZd53FD0CQKt/aXghpcJ7wZllO5V5J46Pvr1zgHpwHw+IH3TipAeAzqDTw964M+OWzzQjVqV1tGuEuFNXLaAubLNja7XqPCHQV4Ck8wT4Vl+zYT6IHMuTScYe7gr/WddzQUr/6MZ6NYVWtBEMKgBKM3n3vRYT7ek38IwqzOzAvaxpnZimYpyJQxOphG1s8VZAb3tSIXyafVOZWzYDlDDP+q3qusSlO7uRHNl4eqnUZOz3c3kI2TBMnGfaEPq4hBh0qtnZEQ1XXDYszCi0nDXBeLRnoxI03No5yuncCMPKQEFXLFF3z4Whtb0/O8doDkW2LMbMJ5ctzGrUKR0TPUWrllbmAlqgGF/40sCqfB9UCznXv2cDhbMUT7vBlK+MtEES/8wYnkkExq/92KJQMmPTwaIADsohpL2Bltbwabg0YqzjnWrzz007iTL1J1PmmcMh0jSRbNl3GeEvkkLumjmDX3jiYxbI4iNdDFVsMc+N5madC1tBTKK0usEMNcgXyN55aptuIKF3juOtZBycO2LQ4Mguy3FxpceL3+ghQosZ0cRwp2sXPBUZshw4W6bg6+OFOb6wmbDhWWHp5GutbIFkrXKOW5hsxgGCwS0ctLI1ioxnQRObCUQfhIJgMBT+EFYU=
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- node index.js
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
